- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Import app_prereq file
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install Python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Import schema_setup file
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Import systemd_setup file
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
